"""empty message

Revision ID: 18c0d9e15e90
Revises: a80d9e1e1600
Create Date: 2023-05-26 15:31:09.280026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18c0d9e15e90'
down_revision = 'a80d9e1e1600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=240),
               type_=sa.String(length=600),
               existing_nullable=True)
        batch_op.alter_column('placement_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.alter_column('placement_type',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(length=600),
               type_=sa.VARCHAR(length=240),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
