"""empty message

Revision ID: 28ff007d5656
Revises: f7b3c3726f33
Create Date: 2023-05-20 16:56:44.286143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28ff007d5656'
down_revision = 'f7b3c3726f33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telegram_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telegram_user_username'), ['username'], unique=True)

    with op.batch_alter_table('bot_user', schema=None) as batch_op:
        batch_op.drop_index('ix_bot_user_email')
        batch_op.drop_index('ix_bot_user_username')

    op.drop_table('bot_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='bot_user_pkey')
    )
    with op.batch_alter_table('bot_user', schema=None) as batch_op:
        batch_op.create_index('ix_bot_user_username', ['username'], unique=False)
        batch_op.create_index('ix_bot_user_email', ['email'], unique=False)

    with op.batch_alter_table('telegram_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telegram_user_username'))

    op.drop_table('telegram_user')
    # ### end Alembic commands ###
