"""empty message

Revision ID: 36543a0b5b47
Revises: 
Create Date: 2023-05-28 00:05:02.190576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36543a0b5b47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telegram_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telegram_user_username'), ['username'], unique=True)

    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_type', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('description', sa.String(length=600), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('placement_type', sa.String(length=10), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['telegram_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_device_type'), ['device_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_placement_type'), ['placement_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_placement_type'))
        batch_op.drop_index(batch_op.f('ix_device_name'))
        batch_op.drop_index(batch_op.f('ix_device_device_type'))
        batch_op.drop_index(batch_op.f('ix_device_description'))

    op.drop_table('device')
    with op.batch_alter_table('telegram_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telegram_user_username'))

    op.drop_table('telegram_user')
    # ### end Alembic commands ###
