"""empty message

Revision ID: 9340c7838ca8
Revises: 282c954f9413
Create Date: 2023-05-25 13:06:02.818910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9340c7838ca8'
down_revision = '282c954f9413'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('placement_type', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_device_placement_type'), ['placement_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_placement_type'))
        batch_op.drop_column('placement_type')

    # ### end Alembic commands ###
