"""empty message

Revision ID: ed54a1e78322
Revises: 18c0d9e15e90
Create Date: 2023-05-26 22:49:19.296734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed54a1e78322'
down_revision = '18c0d9e15e90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_type', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_device_device_type'), ['device_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_device_type'))
        batch_op.drop_column('device_type')

    # ### end Alembic commands ###
